version: 2.1

executors:
  node:
    docker:
      - image: cimg/node:15.14.0
    working_directory: ~/app
  docker_builder:
    docker:
      - image: circleci/buildpack-deps:bionic
        user: root
jobs:
  build_frontend:
    parameters:
      FAUCET_ACCOUNT_PRIV_KEY:
        type: string
    executor: node
    steps:
      - checkout
      - run:
          working_directory: frontend
          name: Npm Install and Prod
          command: npm install && npm run prod
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - ./assets
            - ./templates
            - ./package*.json
            - faucet.js
  build_production:
    executor: node
    steps:
      - checkout
      - run:
          name: Npm Install Production
          command: npm ci --only=production
    

  docker_build:
    executor: docker_builder
    environment:
      DOCKERHUB_REPO: aeternity/aeternal-frontend
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build and push Docker image to DockerHub
          command: |
            docker build -t test-faucet -f Dockerfile .
  

workflows:
  version: 2
  build_push:
    jobs:
      - build_frontend:
          FAUCET_ACCOUNT_PRIV_KEY: "test123"
          filters:
            tags:
              only: /^v.*$/
      - docker_build:
          context: ae-dockerhub
          requires:
            - build_frontend
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*$/
