name: pull-request-cleanup

on:
  pull_request:
    branches: [ master ]
    types: [ closed ]

jobs:
  rollback:
    uses: aeternity/github-actions/.github/workflows/_rollback-gitops.yml@v2.0.0
    secrets: inherit
    with:
      DEPLOY_ENV: stg
      DEPLOY_APP: aepp-faucet
      DEPLOY_VERSION: "pr-${{ github.event.number }}"
      DEPLOY_SUBDOMAIN: "pr-${{ github.event.number }}-faucet"
  delete-tag:
    uses: aeternity/github-actions/.github/workflows/_delete-tag-docker.yml@v2.0.0
    secrets: inherit
    with:
      DOCKERHUB_REPO: "aeternitybot/${{ github.event.repository.name }}"
      DOCKERHUB_TAG: "pr-${{ github.event.number }}"
