name: pull-request

on:
  pull_request:
    branches: [ master ]

jobs:
  publish:
    uses: aeternity/github-actions/.github/workflows/_publish-docker.yml@v1.2.0
    secrets: inherit
    with:
      DOCKERHUB_REPO: "aeternitybot/${{ github.event.repository.name }}"
  deploy:
    uses: aeternity/github-actions/.github/workflows/_deploy-gitops.yml@v1.2.0
    needs: [publish]
    secrets: inherit
    with:
      DEPLOY_ENV: stg
      DEPLOY_APP: aepp-faucet
      DEPLOY_VERSION: "pr-${{ github.event.number }}"
      DEPLOY_HOST_PREFIX: "pr-${{ github.event.number }}-"
